/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/users': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get all users */
    get: operations['getUsers']
    put?: never
    /** Create a new user */
    post: operations['createUser']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/users/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get user by ID */
    get: operations['getUser']
    put?: never
    post?: never
    /** Delete user */
    delete: operations['deleteUser']
    options?: never
    head?: never
    /** Update user */
    patch: operations['updateUser']
    trace?: never
  }
  '/auth/login': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** User login */
    post: operations['login']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/logout': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** User logout */
    post: operations['logout']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    User: {
      /** Format: uuid */
      id: string
      /** Format: email */
      email: string
      firstName: string
      lastName: string
      /** Format: uri */
      avatar?: string
      /** @enum {string} */
      role: 'admin' | 'user' | 'guest'
      /**
       * @default active
       * @enum {string}
       */
      status: 'active' | 'inactive' | 'pending'
      /** Format: date-time */
      createdAt: string
      /** Format: date-time */
      updatedAt?: string
    }
    UsersResponse: {
      data: components['schemas']['User'][]
      meta: components['schemas']['PaginationMeta']
    }
    PaginationMeta: {
      page: number
      limit: number
      total: number
      totalPages: number
    }
    CreateUserRequest: {
      /** Format: email */
      email: string
      firstName: string
      lastName: string
      password: string
      /**
       * @default user
       * @enum {string}
       */
      role: 'admin' | 'user' | 'guest'
    }
    UpdateUserRequest: {
      /** Format: email */
      email?: string
      firstName?: string
      lastName?: string
      /** Format: uri */
      avatar?: string
      /** @enum {string} */
      status?: 'active' | 'inactive' | 'pending'
    }
    LoginRequest: {
      /** Format: email */
      email: string
      password: string
    }
    AuthResponse: {
      user: components['schemas']['User']
      accessToken: string
      refreshToken?: string
    }
    Error: {
      code: string
      message: string
      details?: {
        [key: string]: unknown
      }
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  getUsers: {
    parameters: {
      query?: {
        page?: number
        limit?: number
        search?: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description List of users */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UsersResponse']
        }
      }
    }
  }
  createUser: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateUserRequest']
      }
    }
    responses: {
      /** @description User created */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['User']
        }
      }
      /** @description Invalid input */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
    }
  }
  getUser: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description User details */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['User']
        }
      }
      /** @description User not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
    }
  }
  deleteUser: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description User deleted */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  updateUser: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateUserRequest']
      }
    }
    responses: {
      /** @description User updated */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['User']
        }
      }
    }
  }
  login: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginRequest']
      }
    }
    responses: {
      /** @description Login successful */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AuthResponse']
        }
      }
      /** @description Invalid credentials */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
    }
  }
  logout: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Logout successful */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
}
